# Здесь будет конфиг
  env: "local"
  # уровни логирования
  logger:
    typeLogger: "base"
    appLevel: "Info"
    entLevel: "Debug"
    simLevel: "Info"
  # основные константы модели
  modelConst:
    maxGen: 16
    lengthDNA: 64
    energyPoint: 10
    brain:  "16"
  # основные константы симуляции
  simulation:
    type: "train"
    xSize: 30
    ySize: 30
