# конфиг приложения
  env: "local"
  # уровни логирования
  logger:
    type: "base"
    appLevel: "Info"
    entLevel: "Error"
    simLevel: "Info"
    appPath: "logs/app.log"
    entPath: "logs/ent.log"
    simPath: "logs/sim.log"
  # основные константы модели
  modelConst:
    maxGen: 64
    foodPercent: 25
    lengthDNA: 64
    energyPoint: 5
    brain:  "64"
    loop:
        x: true
        y: true
  # основные константы симуляции
  simulation:
    type: "train"
    X: 15
    Y: 40
    startPop: 100
    endPop: 10
    resourceUpdate: 5
    ageExit: 1000
    mutation: 10
    poison:
        enable: false
        startLevel: 0
    # основные константы симуляции
    console:
        type: "old"
        timeOut: 0
  # место сохранения результатов обучения
  storage:
    type: "file"
    pathAge: "logs/age.txt"
    pathTrain: "logs/train.txt"