# Здесь будет конфиг
  env: "local"
  # уровни логгирования для основных логгеров программы
  logger:
    simLevel: "Info"
    appLevel: "Error"
  # значение основных констант модели
  modelConst:
    maxGen: 16
    lengthDNA: 64
    energyPoint: 10
    brain:  "16"