Server:
  ip: "localhost"
  port: "8080"
ALSS:
  TimeStop: 500
  Stats: False
  World:
    x: 100
    y: 100
  Agent:
    typeGenome: "RAND"
    sizeGenome: 64
    maxGen: 32
    maxAge: 1500
    maxEnergy: 1500
    baseEnergy: 100
    actionCost: 1
    pollutionCost: 10
    huntingCoefficient: 50
    birthCost: 250
    mutationCount: 1
Logger:
  path: "logs/app.log"
  level: "Info"