# Здесь будет конфиг
  env: "local"
  # уровни логирования
  logger:
    typeLogger: "base"
    appLevel: "Info"
    entLevel: "Error"
    simLevel: "Info"
    appPath: "logs/app.log"
    entPath: "logs/ent.log"
    simPath: "logs/sim.log"
  # основные константы модели
  modelConst:
    maxGen: 16
    lengthDNA: 64
    energyPoint: 10
    brain:  "16"
  # основные константы симуляции
  simulation:
    typeSimulation: "train"
    X: 15
    Y: 50
    startPop: 100
    endPop: 10
    startPoison: 0
    resourceUpdate: 10
    ageExit: 1000
    mutation: 10